import Foundation
import NippoCore

print("nippo-tests")
runDatabaseTests()
runAppLogTests()
runSettingsTests()
runQuietDayTests()
runJapaneseHolidaysTests()
runDayKeyTests()
runWorkStartTests()
runTaskOutlineTests()
runLinkExtractorTests()
runNextEventTests()
runHeroPolicyTests()
runDayTimelineTests()
runCreatureFitTests()
runBreakReminderTests()
runEnglishTests()
runEnglishRoundTests()
runEnglishSyncTests()
T.finish()
